### PR TITLE
Replacing Guava with Available Routines where possible

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@dblock Can you look over this and see if you are ok with all of this?  I haven't ran any official tests other than junits at this point.  Most is pretty straight forward.  Using the xml bind library is not so straight forwards but does solve base64 issues without diving into restricted areas of the oracle jdk.

**Comment by dblock** [comment]
This looks good, I would run tests obviously before merging anything.

**Comment by dblock** [comment]
I don't love that we're using all kinds of Base 64 encoding/decoding, btw.

**Comment by hazendaz** [comment]
Closing this pull request.  Will come back with only java 7 related changes and no base64 changes so we can remain consistent.

**Pull request closed without merging**
