### PR TITLE
Fix handle leak in LSASS

### PR DESCRIPTION
**Pull request by malaporte**
I noticed that the handle count of the LSASS process would continuously go up on servers using Waffle. Stopping the Java process would result in the handle count to immediately drop back to a normal value.

After a bit of digging I found out that the `WindowsCredentialsHandleImpl` allocated in `acceptSecurityToken` was never disposed, causing the leak. To fix that, I've arranged for this object lifetime to be determined by the associated `WindowsSecurityContextImpl`, since everywhere I could find the server credentials always end up tightly bound to one of those --- that is unless someone is calling `WindowsAuthProviderImpl.getCurrent` directly, but in this case the caller is responsible of calling `dispose` on it.

With this modification the handle count of both the server process and LSASS remains stable.

### CODE REVIEW

**Comment by hazendaz** [comment]
Can you run a git pull --rebase upstream master against you code so it drops the commit sync on master?


I'll take a look at this tonight.  For your needs, are you using java 6 or 7?  That will help me decide on backport to 1.7.x.


Thanks,


Jeremy


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 1:54 AM -0700, "Martin Laporte" <notifications@github.com> wrote:
I noticed that the handle count of the LSASS process would continuously go up on servers using Waffle. Stopping the Java process would result in the handle count to immediately drop back to a normal value.

After a bit of digging I found out that the `WindowsCredentialsHandleImpl` allocated in `acceptSecurityToken` was never disposed, causing the leak. To fix that, I've arranged for this object lifetime to be determined by the associated `WindowsSecurityContextImpl`, since everywhere I could find the server credentials always end up tightly bound to one of those --- that is unless someone is calling `WindowsAuthProviderImpl.getCurrent` directly, but in this case the caller is responsible of calling `dispose` on it.

With this modification the handle count of both the server process and LSASS remains stable.
You can view, comment on, or merge this pull request online at:

  https://github.com/dblock/waffle/pull/239

-- Commit Summary --

  * Release the server credentials through the dispose() method on IWindowsSecurityContext.
  * Bring up-to-date with master.
  * Remove IDE file I added by mistake.

-- File Changes --

    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java (2)
    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java (35)
    M Source/JNA/waffle-tests/src/test/java/waffle/servlet/NegotiateSecurityFilterTests.java (4)
    M Source/JNA/waffle-tests/src/test/java/waffle/windows/auth/WindowsAuthProviderTests.java (6)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)

-- Patch Links --

https://github.com/dblock/waffle/pull/239.patch
https://github.com/dblock/waffle/pull/239.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/waffle/pull/239

**Comment by hazendaz** [comment]
I'm good with change otherwise.  Can you add a note to setting the null to further note it's intentional so it's never mistakenly removed.


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 4:02 AM -0700, <jeremylandis@hotmail.com> wrote:
Can you run a git pull --rebase upstream master against you code so it drops the commit sync on master?


I'll take a look at this tonight.  For your needs, are you using java 6 or 7?  That will help me decide on backport to 1.7.x.


Thanks,


Jeremy


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 1:54 AM -0700, "Martin Laporte" <notifications@github.com> wrote:
I noticed that the handle count of the LSASS process would continuously go up on servers using Waffle. Stopping the Java process would result in the handle count to immediately drop back to a normal value.

After a bit of digging I found out that the `WindowsCredentialsHandleImpl` allocated in `acceptSecurityToken` was never disposed, causing the leak. To fix that, I've arranged for this object lifetime to be determined by the associated `WindowsSecurityContextImpl`, since everywhere I could find the server credentials always end up tightly bound to one of those --- that is unless someone is calling `WindowsAuthProviderImpl.getCurrent` directly, but in this case the caller is responsible of calling `dispose` on it.

With this modification the handle count of both the server process and LSASS remains stable.
You can view, comment on, or merge this pull request online at:

  https://github.com/dblock/waffle/pull/239

-- Commit Summary --

  * Release the server credentials through the dispose() method on IWindowsSecurityContext.
  * Bring up-to-date with master.
  * Remove IDE file I added by mistake.

-- File Changes --

    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java (2)
    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java (35)
    M Source/JNA/waffle-tests/src/test/java/waffle/servlet/NegotiateSecurityFilterTests.java (4)
    M Source/JNA/waffle-tests/src/test/java/waffle/windows/auth/WindowsAuthProviderTests.java (6)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)

-- Patch Links --

https://github.com/dblock/waffle/pull/239.patch
https://github.com/dblock/waffle/pull/239.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/waffle/pull/239

**Comment by hazendaz** [comment]
And please add a changelog entry


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 4:23 AM -0700, <jeremylandis@hotmail.com> wrote:
I'm good with change otherwise.  Can you add a note to setting the null to further note it's intentional so it's never mistakenly removed.


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 4:02 AM -0700, <jeremylandis@hotmail.com> wrote:
Can you run a git pull --rebase upstream master against you code so it drops the commit sync on master?


I'll take a look at this tonight.  For your needs, are you using java 6 or 7?  That will help me decide on backport to 1.7.x.


Thanks,


Jeremy


Sent by Outlook for Android





On Tue, Sep 8, 2015 at 1:54 AM -0700, "Martin Laporte" <notifications@github.com> wrote:
I noticed that the handle count of the LSASS process would continuously go up on servers using Waffle. Stopping the Java process would result in the handle count to immediately drop back to a normal value.

After a bit of digging I found out that the `WindowsCredentialsHandleImpl` allocated in `acceptSecurityToken` was never disposed, causing the leak. To fix that, I've arranged for this object lifetime to be determined by the associated `WindowsSecurityContextImpl`, since everywhere I could find the server credentials always end up tightly bound to one of those --- that is unless someone is calling `WindowsAuthProviderImpl.getCurrent` directly, but in this case the caller is responsible of calling `dispose` on it.

With this modification the handle count of both the server process and LSASS remains stable.
You can view, comment on, or merge this pull request online at:

  https://github.com/dblock/waffle/pull/239

-- Commit Summary --

  * Release the server credentials through the dispose() method on IWindowsSecurityContext.
  * Bring up-to-date with master.
  * Remove IDE file I added by mistake.

-- File Changes --

    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java (2)
    M Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java (35)
    M Source/JNA/waffle-tests/src/test/java/waffle/servlet/NegotiateSecurityFilterTests.java (4)
    M Source/JNA/waffle-tests/src/test/java/waffle/windows/auth/WindowsAuthProviderTests.java (6)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java (4)
    M Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java (6)

-- Patch Links --

https://github.com/dblock/waffle/pull/239.patch
https://github.com/dblock/waffle/pull/239.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/waffle/pull/239

**Comment by malaporte** [comment]
Done for all your requests, by the way.

About your question, we're using Java 8. Right now I'm using a build I produced internally so no hurry for an "official" version.

**Comment by hazendaz** [comment]
Perfect.  I'll get to this tonight.  Thanks


Sent by Outlook for Android





On Wed, Sep 9, 2015 at 1:36 AM -0700, "Martin Laporte" <notifications@github.com> wrote:
Done for all your requests, by the way.

About your question, we're using Java 8. Right now I'm using a build I produced internally so no hurry for an "official" version.

---

**Comment by dblock** [comment]
:+1: This was a good find and smack in the middle of the default execution path.

**Comment by gstanchev** [comment]
Handle leak? Hurry! Hurry an official fix version! ☺

**Comment by hazendaz** [comment]
I'll try to get this released over the next couple of days.  This will be in the first official 1.8.x version of waffle.  That version requires java 7.  As such, I'm inclined to back port this as well to 1.7.x series for those users still "forced" to be on java 6 as we promised support through 2016.

**Comment by hazendaz** [comment]
1.8.0 release should be available in the next few hours.  It requires at least jdk7 to use.  I plan to back port this to 1.7.5 release as soon as I get some time.

**Pull request merged**
