### PR TITLE
Support authorization in service provider

### PR DESCRIPTION
**Pull request by csms**
Hi. Please review and merge if you like and have time.

I appologize for any mistakes.

### CODE REVIEW

**Comment by csms** [comment]
Hi - I don't have access to spring 4 within the project so that will be hard. I'll see if I'm competent enough to write a proper testcase. I'll update the CHANGELOG. Where do I put the documentation updates?

**Comment by hazendaz** [comment]
Changeling is on root of master.  Any other docs are under docs on root.  Spring 4 is at the moment identical to spring 3 so blindly adding as long as it builds is good enough.  Look at overall setup of development as spring security 4 needs installed to your local repo.  There is a batch file under third party to do that.  Let me know if you need anything else.

--- Original Message ---

**Comment by csms** [comment]
Oh - you squashed it aswell? Sorry, I was going to do that for you when I was done :-)

**Comment by csms** [comment]
Cool, you guys are awesome.

**Comment by hazendaz** [comment]
No problem.  This looked safe and I was doing some other work so took it.  If you got a little more coming just open a new pull request and I'll take it.  When you are ready for an official release let me know and I'll get that out there as well.  I thought something might be left in the works but since this doesn't necessarily change any current usage it was good to go.

--- Original Message ---

**Comment by dblock** [comment]
No @csms, *you* are awesome :)

**Pull request merged**
